# Generated by Django 4.0.1 on 2022-04-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_customeraddress_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle'),
        ),
    ]
