# Generated by Django 4.0.1 on 2022-04-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_pagemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Email'),
        ),
    ]
