# Generated by Django 4.0.1 on 2022-04-18 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.AddField(
            model_name='order',
            name='order_finish',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fin de pedido'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='comenso de pedido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de pedido'),
        ),
    ]
