# Generated by Django 4.0.1 on 2022-04-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_item_description_de_item_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_order', to='main.Order', verbose_name='Pedidos'),
        ),
    ]
