# Generated by Django 4.0.1 on 2022-04-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_item_slide_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='youtube',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Video'),
        ),
    ]
