# Generated by Django 4.0.1 on 2022-04-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_item_extra_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nombre')),
                ('text', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Mensaje',
            },
        ),
    ]
