# Generated by Django 4.0.1 on 2022-04-18 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_cart_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_finish',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='comenso de pedido'),
        ),
    ]
