# Generated by Django 4.0.1 on 2022-04-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_order_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de dueño')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle')),
                ('number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numero')),
                ('iban', models.CharField(blank=True, max_length=255, null=True, verbose_name='Iban')),
                ('banco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Banco')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion de Banco')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Fotos de pedido')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='latitud')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='longitud')),
                ('send_email_to_owner', models.BooleanField(default=False, verbose_name='Mandar email a dueño')),
                ('send_email_to_customer', models.BooleanField(default=False, verbose_name='Mandar email a cliente')),
            ],
            options={
                'verbose_name': 'Dueño',
            },
        ),
    ]
