# Generated by Django 4.0.1 on 2022-04-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_pageinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description_de',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='item',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='item',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='item',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='item',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='item',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='info_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='info_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='info_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='title_de',
            field=models.CharField(default='info', max_length=255, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='title_en',
            field=models.CharField(default='info', max_length=255, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='title_es',
            field=models.CharField(default='info', max_length=255, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='pagemessage',
            name='text_de',
            field=models.TextField(null=True, verbose_name='Mensaje'),
        ),
        migrations.AddField(
            model_name='pagemessage',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Mensaje'),
        ),
        migrations.AddField(
            model_name='pagemessage',
            name='text_es',
            field=models.TextField(null=True, verbose_name='Mensaje'),
        ),
    ]
