# Generated by Django 4.0.1 on 2022-04-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slide',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Slide'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
