# Generated by Django 4.0.1 on 2022-04-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_storage_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='iban',
        ),
        migrations.AddField(
            model_name='storage',
            name='stripe_public',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='stripe_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
